version: "3"

services:
  app:
    depends_on:
      - database
    image: stord-assessment:test
    build:
      context: .
      args:
        MIX_ENV: test
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
        DB_HOSTNAME: database
        DB_DATABASE: remote_assessment_test
  database:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: remote_assessment_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
